import tpc6 
obras = tpc6.lerObras()
Nobras = tpc6.contaObras(obras)
ordemTitAno = tpc6.obrasTitAno(obras)
ordemAnoTit = tpc6.obrasAnoTit(obras)
ordemAlfComp = tpc6.ordenaCompositores(obras)
distribAnos = tpc6.distribAnos(obras)
distribPeriodos = tpc6.distribPeriodos(obras)
distribComp = tpc6.distribCompositor(obras)

print("################################################### PROGRAMA #########################################################")
#print()
#print("Datasset")
#print()
print(obras)
print()
print("-------------------------------------------------------------------------------")
print("Numero de obras")
print()
print(Nobras)
print()
print("-------------------------------------------------------------------------------")
print("Tabela de dados")
print()
tpc6.imprimeObras(obras)
print()
print("-------------------------------------------------------------------------------")
print("Ordena tuplo(titulo,ano) por ordem alfabética")
print()
print(ordemTitAno)
print()
print("-------------------------------------------------------------------------------")
print("Ordena tuplo(titulo,ano) por ordem numérica crescente")
print()
print(ordemAnoTit)
print()
print("-------------------------------------------------------------------------------")
print("Lista ordenada de compositores")
print()
print(ordemAlfComp)
print()
print("-------------------------------------------------------------------------------")
print("Distribuição por Periodos")
print()
print(tpc6.distribPeriodos(obras))
print(tpc6.criaGrafico(distribPeriodos))
print()
print("-------------------------------------------------------------------------------")
print("Distribuição por anos")
print()
print(tpc6.distribAnos(obras))
print(tpc6.criaGrafico(distribAnos))
print()
print("-------------------------------------------------------------------------------")
print("Distribuição por Compositos")
print()
print(tpc6.distribCompositor(obras))
print(tpc6.criaGrafico(distribComp))
print()
print("-------------------------------------------------------------------------------")
print("Problema da inversão de estrutura")
print()
tpc6.distribCompObras(obras)
print()

